### ISSUE TITLE
Unable to read messages

### ISSUE THREAD

**Issue by simzcool** [Misnad/UoPeopleCampus2#4]
[]()![Point Blur_Feb182022_055833.jpg](https://user-images.githubusercontent.com/35952320/154615513-7a3ee428-d36a-4657-a726-06b65a7b0ca4.jpg)

**Comment by Misnad** [comment]
You can click the messages button on the bottom right to access your messages.

![Untitled](https://user-images.githubusercontent.com/71584961/154700874-8ca0b995-49f5-4b5f-b55c-176201dc3ba1.png)
